"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import sys
import os
from pathlib import Path

# Detect if running as a standalone executable (PyInstaller, Nuitka)
IS_FROZEN = getattr(sys, 'frozen', False)

if IS_FROZEN:
    # sys._MEIPASS is the internal path where PyInstaller extracts/locates files.
    # In newer PyInstaller versions with --onedir, this points to the '_internal' folder.
    meipass = getattr(sys, '_MEIPASS', None)
    if meipass:
        BUNDLE_DIR = Path(meipass)
    else:
        BUNDLE_DIR = Path(sys.executable).resolve().parent
    
    # BASE_DIR is the permanent folder (where the EXE resides)
    # If using --onedir, the EXE is in the root, and code is in _internal.
    # BUT sometimes PyInstaller behavior varies.
    BASE_DIR = Path(sys.executable).resolve().parent
    
    pass
else:
    BUNDLE_DIR = Path(__file__).resolve().parent.parent
    BASE_DIR = BUNDLE_DIR

# Custom setting for conditional logic in URLs/Views
IS_FROZEN = IS_FROZEN

# Keep the original BASE_DIR name for compatibility with variables below,
# but internally use BUNDLE_DIR for things that are packaged.
    
# SECURITY WARNING: keep the secret key used in production secret!
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ey_(_35rg!!m&if9_sp6@)d4=25a%**g9!x0!9ul0+!=kluv(d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not IS_FROZEN

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'manager',
    'infrastructure',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', # Must be after SessionMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'manager.middleware.VersionEnforcementMiddleware',  # Version enforcement for force updates
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BUNDLE_DIR / 'templates',
            BUNDLE_DIR / 'manager' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static',
                'django.template.context_processors.media',
                'django.template.context_processors.i18n',
                'manager.context_processors.version_info',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Global Date Format: DD/MM/YYYY
USE_L10N = False
DATE_FORMAT = 'd/m/Y'
SHORT_DATE_FORMAT = 'd/m/Y'
DATETIME_FORMAT = 'd/m/Y H:i'
SHORT_DATETIME_FORMAT = 'd/m/Y H:i'


TIME_ZONE = 'Africa/Cairo'

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ('en', 'English'),
    ('ar', 'Arabic'),
]

# LAST UPDATED: 2026-01-11 20:20 (Force Reload)
import os
LOCALE_PATHS = [
    os.path.join(BUNDLE_DIR, 'locale'),
]


# Fix for Mime Types on Windows 7
import mimetypes
mimetypes.add_type("text/css", ".css", True)
mimetypes.add_type("text/javascript", ".js", True)

if IS_FROZEN:
    pass

STATIC_URL = '/static/'
_static_dir = BUNDLE_DIR / 'static'
STATICFILES_DIRS = [str(_static_dir)] if _static_dir.exists() else []
STATIC_ROOT = str(BUNDLE_DIR / 'staticfiles')

if IS_FROZEN:
    pass

# Use WhiteNoise to serve static files
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.StaticFilesStorage",
    },
}

# WhiteNoise settings for correct behavior in both Dev and Prod
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = DEBUG

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Authentication Settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

from django.utils.translation import gettext_lazy as _
from django.urls import reverse_lazy
from django.templatetags.static import static

UNFOLD = {
    "SITE_TITLE": "Internet 2000",
    "SITE_HEADER": "Internet 2000 Admin",
    "SITE_URL": "/",
    "COLORS": {
        "primary": {
            "50": "255 241 242",
            "100": "255 228 230",
            "200": "254 205 211",
            "300": "253 164 175",
            "400": "251 113 133",
            "500": "244 63 94",
            "600": "225 29 72",
            "700": "190 18 60",
            "800": "159 18 57",
            "900": "136 19 55",
            "950": "76 5 25",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("App Control"),
                "separator": True,
                "items": [
                    {
                        "title": _("Live Dashboard"),
                        "icon": "dashboard",
                        "link": "/",
                    },
                ],
            },
            {
                "title": _("Operations"),
                "separator": True,
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                    {
                        "title": _("Tables"),
                        "icon": "table_restaurant",
                        "link": reverse_lazy("admin:manager_table_changelist"),
                    },
                    {
                        "title": _("Orders"),
                        "icon": "shopping_cart",
                        "link": reverse_lazy("admin:manager_order_changelist"),
                    },
                    {
                        "title": _("History"),
                        "icon": "receipt_long",
                        "link": reverse_lazy("admin:manager_tablesession_changelist"),
                    },
                ],
            },
            {
                "title": _("Catalog"),
                "separator": True,
                "items": [
                     {
                        "title": _("Menu Items"),
                        "icon": "restaurant_menu",
                        "link": reverse_lazy("admin:manager_item_changelist"),
                    },
                    {
                        "title": _("System Settings"),
                        "icon": "settings",
                        "link": reverse_lazy("admin:infrastructure_globalsettings_changelist"),
                    },
                ],
            },
            {
                "title": _("Users & Access"),
                "separator": True,
                "items": [
                     {
                        "title": _("Users"),
                        "icon": "people",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": _("Groups"),
                        "icon": "groups",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
        ],
    },
}


