# Generated by Django 6.0 on 2026-02-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_charge_per_person', models.DecimalField(decimal_places=2, default=25.0, max_digits=10)),
                ('active_shift', models.CharField(choices=[('MORNING', 'Morning'), ('NIGHT', 'Night')], default='MORNING', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Global Settings',
                'db_table': 'manager_globalsettings',
            },
        ),
    ]
