# Generated by Django 6.0 on 2026-02-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='auto_logout_minutes',
            field=models.IntegerField(default=0, help_text='Wait minutes before automatic logout. Set to 0 to disable.'),
        ),
    ]
