# Generated by Django 6.0 on 2026-02-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_globalsettings_auto_logout_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='auto_logout_target',
            field=models.CharField(choices=[('ALL', 'All Users'), ('NON_ADMIN', 'Users except Admin')], default='ALL', help_text='Select which users are subject to automatic logout.', max_length=10),
        ),
    ]
