# Generated by Django 6.0 on 2026-02-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_globalsettings_auto_logout_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='last_global_logout',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last triggered global logout.', null=True),
        ),
    ]
