# Generated by Django 6.0 on 2026-02-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_globalsettings_last_global_logout'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='last_global_logout_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address that triggered the last global logout.', null=True),
        ),
    ]
