# Generated by Django 6.0 on 2026-02-15 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('is_drink', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PongLobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('is_ready', models.BooleanField(default=False)),
                ('y_pos', models.IntegerField(default=250)),
                ('bx', models.IntegerField(default=375)),
                ('by', models.IntegerField(default=292)),
                ('bdx', models.IntegerField(default=5)),
                ('bdy', models.IntegerField(default=-5)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('capacity', models.IntegerField(default=50)),
                ('is_occupied', models.BooleanField(default=False)),
                ('current_people', models.IntegerField(default=1)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuickFireItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quickfire_items', to='manager.item')),
            ],
            options={
                'verbose_name': 'Quick Fire Item',
                'verbose_name_plural': 'Quick Fire Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StickyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('color', models.CharField(default='bg-soft-yellow', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.table')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('order_source', models.CharField(choices=[('DIRECT', 'Direct'), ('QR', 'QR Menu')], default='DIRECT', max_length=10)),
                ('is_served', models.BooleanField(default=False)),
                ('shift', models.CharField(choices=[('MORNING', 'Morning'), ('NIGHT', 'Night')], default='MORNING', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.item')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.table')),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='manager_ord_timesta_22d1e5_idx'), models.Index(fields=['is_paid'], name='manager_ord_is_paid_301626_idx'), models.Index(fields=['order_source'], name='manager_ord_order_s_6311e3_idx')],
            },
        ),
        migrations.CreateModel(
            name='TableSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('people_count', models.IntegerField()),
                ('items_summary', models.TextField(default='')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('check_out_time', models.DateTimeField(auto_now=True)),
                ('shift', models.CharField(choices=[('MORNING', 'Morning'), ('NIGHT', 'Night')], default='MORNING', max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['check_out_time'], name='manager_tab_check_o_3d85cb_idx')],
            },
        ),
    ]
