# Generated by Django 6.0 on 2026-02-17 07:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='PongLobby',
        ),
        migrations.RemoveIndex(
            model_name='tablesession',
            name='manager_tab_check_o_3d85cb_idx',
        ),
        migrations.RenameField(
            model_name='tablesession',
            old_name='check_in_time',
            new_name='session_start_time',
        ),
        migrations.AddField(
            model_name='tablesession',
            name='checkout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='tablesession',
            index=models.Index(fields=['checkout_time'], name='manager_tab_checkou_c2443d_idx'),
        ),
        migrations.RemoveField(
            model_name='tablesession',
            name='check_out_time',
        ),
    ]
