# Generated by Django 6.0 on 2026-01-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_item_remove_order_item_name_remove_order_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='capacity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
