# Generated by Django 6.0 on 2026-02-22 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_delete_ponglobby_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Action Log', 'verbose_name_plural': 'Action Logs'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='stickynote',
            options={'verbose_name': 'Sticky Note', 'verbose_name_plural': 'Sticky Notes'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'Table', 'verbose_name_plural': 'Tables'},
        ),
        migrations.AlterModelOptions(
            name='tablesession',
            options={'verbose_name': 'Table Session', 'verbose_name_plural': 'Table Sessions'},
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action_type',
            field=models.CharField(max_length=50, verbose_name='Action Type'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='details',
            field=models.TextField(verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.table', verbose_name='Table'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_drink',
            field=models.BooleanField(default=False, verbose_name='Is Drink'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Is Paid'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_served',
            field=models.BooleanField(default=False, verbose_name='Is Served'),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_source',
            field=models.CharField(choices=[('DIRECT', 'Direct'), ('QR', 'QR Menu')], default='DIRECT', max_length=10, verbose_name='Order Source'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Paid At'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shift',
            field=models.CharField(choices=[('MORNING', 'Morning'), ('NIGHT', 'Night')], default='MORNING', max_length=10, verbose_name='Shift'),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.table', verbose_name='Table'),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Transaction Price'),
        ),
        migrations.AlterField(
            model_name='quickfireitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quickfire_items', to='manager.item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='quickfireitem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='stickynote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='stickynote',
            name='color',
            field=models.CharField(default='bg-soft-yellow', max_length=50, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='stickynote',
            name='content',
            field=models.TextField(blank=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='stickynote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='stickynote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.IntegerField(default=50, verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='table',
            name='current_people',
            field=models.IntegerField(default=1, verbose_name='Current People'),
        ),
        migrations.AlterField(
            model_name='table',
            name='is_occupied',
            field=models.BooleanField(default=False, verbose_name='Is Occupied'),
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='table',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Opened At'),
        ),
        migrations.AlterField(
            model_name='tablesession',
            name='checkout_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Checkout Time'),
        ),
        migrations.AlterField(
            model_name='tablesession',
            name='items_summary',
            field=models.TextField(default='', verbose_name='Items Summary'),
        ),
        migrations.AlterField(
            model_name='tablesession',
            name='people_count',
            field=models.IntegerField(verbose_name='People Count'),
        ),
        migrations.AlterField(
            model_name='tablesession',
            name='session_start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Session Start Time'),
        ),
        migrations.AlterField(
            model_name='tablesession',
            name='shift',
            field=models.CharField(choices=[('MORNING', 'Morning'), ('NIGHT', 'Night')], default='MORNING', max_length=10, verbose_name='Shift'),
        ),
        migrations.AlterField(
            model_name='tablesession',
            name='table_number',
            field=models.IntegerField(verbose_name='Table Number'),
        ),
        migrations.AlterField(
            model_name='tablesession',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='tablesession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
