# Generated by Django 6.0 on 2026-02-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_actionlog_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='pending_reset',
            field=models.BooleanField(default=False, verbose_name='Pending Reset'),
        ),
    ]
