# Generated by Django 6.0 on 2026-01-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_table_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='current_people',
            field=models.IntegerField(default=0),
        ),
    ]
