# Generated by Django 6.0 on 2026-01-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_table_current_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='min_charge_per_person',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='table',
            name='current_people',
            field=models.IntegerField(),
        ),
    ]
