# Generated by Django 6.0 on 2026-02-23 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_table_pending_reset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StickyNote',
        ),
    ]
