# Generated by Django 6.0 on 2026-03-14 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_delete_stickynote'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_menu_entries', to='manager.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Quick Menu Item',
                'verbose_name_plural': 'Quick Menu Items',
                'ordering': ['order', 'id'],
            },
        ),
    ]
