# Generated by Django 6.0 on 2026-01-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_tablesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesession',
            name='items_summary',
            field=models.TextField(default=''),
        ),
    ]
