# Generated by Django 6.0 on 2026-01-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_tablesession_items_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_charge_per_person', models.DecimalField(decimal_places=2, default=25.0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Global Settings',
            },
        ),
        migrations.RemoveField(
            model_name='table',
            name='min_charge_per_person',
        ),
    ]
