# Generated by Django 6.0 on 2026-01-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_globalsettings_remove_table_min_charge_per_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.IntegerField(default=50),
        ),
    ]
