# Generated by Django 6.0 on 2026-01-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_alter_table_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='current_people',
            field=models.IntegerField(default=1),
        ),
    ]
