# Generated by Django 6.0 on 2026-01-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_order_description_order_transaction_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_drink',
            field=models.BooleanField(default=False),
        ),
    ]
