# Generated by Django 6.0 on 2026-01-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
