# Generated by Django 6.0 on 2026-01-10 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_table_opened_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.item'),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.table'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['timestamp'], name='manager_ord_timesta_22d1e5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_paid'], name='manager_ord_is_paid_301626_idx'),
        ),
        migrations.AddIndex(
            model_name='tablesession',
            index=models.Index(fields=['check_out_time'], name='manager_tab_check_o_3d85cb_idx'),
        ),
    ]
