# Generated by Django 6.0 on 2026-01-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_source',
            field=models.CharField(choices=[('DIRECT', 'Direct'), ('QR', 'QR Menu')], default='DIRECT', max_length=10),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_source'], name='manager_ord_order_s_6311e3_idx'),
        ),
    ]
