# Generated by Django 6.0 on 2026-01-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_order_order_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_served',
            field=models.BooleanField(default=False),
        ),
    ]
