# Generated by Django 6.0 on 2026-02-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_ponglobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponglobby',
            name='y_pos',
            field=models.IntegerField(default=250),
        ),
    ]
