# Generated by Django 6.0 on 2026-02-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0022_ponglobby_y_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponglobby',
            name='bdx',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='ponglobby',
            name='bdy',
            field=models.IntegerField(default=-5),
        ),
        migrations.AddField(
            model_name='ponglobby',
            name='bx',
            field=models.IntegerField(default=375),
        ),
        migrations.AddField(
            model_name='ponglobby',
            name='by',
            field=models.IntegerField(default=292),
        ),
    ]
