# Generated by Django 6.0 on 2026-02-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_ponglobby_bdx_ponglobby_bdy_ponglobby_bx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='active_shift',
            field=models.CharField(choices=[('MORNING', 'Morning'), ('NIGHT', 'Night')], default='MORNING', max_length=10),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='shift',
            field=models.CharField(choices=[('MORNING', 'Morning'), ('NIGHT', 'Night')], default='MORNING', max_length=10),
        ),
    ]
