# Generated by Django 6.0 on 2026-02-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0024_globalsettings_active_shift_tablesession_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shift',
            field=models.CharField(choices=[('MORNING', 'Morning'), ('NIGHT', 'Night')], default='MORNING', max_length=10),
        ),
    ]
