# Generated by Django 6.0 on 2026-02-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0025_order_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
