# Generated by Django 6.0 on 2026-02-12 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0026_order_paid_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickFireItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quickfire_items', to='manager.item')),
            ],
            options={
                'verbose_name': 'Quick Fire Item',
                'verbose_name_plural': 'Quick Fire Items',
                'ordering': ['order'],
            },
        ),
    ]
